### ISSUE TITLE
SDA and SCL have been swapped in error.

### ISSUE THREAD

**Issue by g6pde** [Biacco42/ProMicroKiCad#4]
SDA and SCL have been swapped in error in the schematic.
SDA should be pin 5 and SCL pin 6 counting from pin 1 in top left. I am using a pitcure from the Sparkfun site as a reference. https://learn.sparkfun.com/tutorials/pro-micro--fio-v3-hookup-guide/hardware-overview-pro-micro

**Comment by Biacco42** [comment]
This issue has been solved by #5 . Thanks. And sorry for too late my reactions.
